/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package post;

import java.awt.Image;
import java.awt.event.MouseEvent;

import javax.swing.ImageIcon;

import page.HomePage;
import page.PhotoPage;
import page.ProfilePage;

/**
 *
 * @author emirh
 */
public class HomePhotoPanel extends javax.swing.JPanel {
	
	private String stalkerUsername;
	private String photoUsername;
    private int photoNumber;
    /**
     * Creates new form HomePhotoPanel
     */
    public HomePhotoPanel(String photoUsername, String stalkerUsername ,int photoNumber) {
    	this.stalkerUsername = stalkerUsername;
    	this.photoUsername = photoUsername;
    	this.photoNumber = photoNumber;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profilePhoto = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();

        username.setText(photoUsername);
        
        String path = "./src/userInfo/"+photoUsername;
        ImageIcon photoIcon = new ImageIcon(path+"/Posts/"+photoNumber+".png");
        ImageIcon resizedPhotoIcon = new ImageIcon(photoIcon.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH));
        photo.setIcon(resizedPhotoIcon);
        photo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                photoMouseClicked(evt);
            }
        });
        
        ImageIcon profilePhotoIcon = new ImageIcon(path+"/profilePhoto.png");
        ImageIcon resizedProfilePhotoIcon = new ImageIcon(profilePhotoIcon.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH));
        profilePhoto.setIcon(resizedProfilePhotoIcon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(profilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(profilePhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void photoMouseClicked(MouseEvent evt) {
		// TODO Auto-generated method stub
		PhotoPage photo = new PhotoPage(photoUsername,stalkerUsername,photoNumber,null);
		photo.setVisible(true);
		photo.pack();
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel photo;
    private javax.swing.JLabel profilePhoto;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
